#ifndef CONSTANTS_H_
#define CONSTANTS_H_

#define BUFLEN 2048
#define COUNTER_BLOCK_SIZE 16
#define COUNTER_BLOCK_INC 8

#define MAX_POSITION_DISTANCE 500
#define MAX_FLUSH_STRING_SIZE 10000

#endif // CONSTANTS_H_
